# Generated by Django 5.0.3 on 2024-03-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'verbose_name': 'Flashcard', 'verbose_name_plural': 'Flashcards'},
        ),
    ]
